# Generated by Django 5.2.8 on 2025-11-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='especie',
            field=models.CharField(choices=[('cao', 'Cão'), ('gato', 'Gato')], max_length=10),
        ),
    ]
